apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: phonebook
    {{- include "operator.labels" . | nindent 4 }}
  name: phonebook-providers
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if ((.Values.serviceAccount).annotations) }}
      {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
    {{- end }}



