solver:
  enabled: false
  certManager:
    serviceAccount:
      name: cert-manager
      namespace: cert-manager
  privateKeySecretRef:
    name: phonebook-solver

controller:
  image: "ghcr.io/pier-oliviert/phonebook:v0.3.7"
